# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ "main" ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ssh g++ git libboost-atomic-dev libboost-thread-dev libboost-system-dev libboost-date-time-dev libboost-regex-dev libboost-filesystem-dev libboost-random-dev libboost-chrono-dev libboost-serialization-dev libwebsocketpp-dev openssl libssl-dev ninja-build libspdlog-dev libmbedtls-dev libboost-all-dev libconfig++-dev libsctp-dev libfftw3-dev vim libcpprest-dev libusb-1.0-0-dev net-tools smcroute python-psutil python3-pip clang-tidy gpsd gpsd-clients libgps-dev
          sudo snap install cmake --classic
          sudo pip3 install cpplint
          sudo apt install libsoapysdr-dev soapysdr-tools
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          run_tests: OFF
          unit_test_build: -Dtest=ON
          create_package: YES
          package_generator: exe
  
      - name: 上传附件
        uses: actions/upload-artifact@v4
        with:
          path: build/*.exe
  
      - name: 下载附件
        uses: actions/download-artifact@v4
