# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install \
            build-essential cmake ninja-build pkg-config \
            libboost-dev libssl-dev zlib1g-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.5.0"
          archives: icu qtbase qtsvg qttools
      - name: 上传附件
        uses: actions/upload-artifact@v4
        with:
          path: build/*.exe
      - name: 下载附件
        uses: actions/download-artifact@v4
