# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install conan
        run: |
          python3 -m pip install --upgrade pip
          pip3 install conan
          pip3 install conan --upgrade
          conan --version
          conan profile new default --detect
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          run_tests: OFF
          unit_test_build: -Dtest=ON
          create_package: YES
          package_generator: exe
      - name: 上传附件
        uses: actions/upload-artifact@v4
        with:
          path: build/*.exe
      - name: 下载附件
        uses: actions/download-artifact@v4
