# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          target: 'desktop'

      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 1
            
      - name: build-mingw
        shell: cmd
        run: |
          mkdir build
          cd build
          qmake -r CONFIG+=release ..\WC3ModManager.pro
          make
      - name: package
        shell: cmd
        run: |
          windeployqt build\release\WC3ModManager.exe
            
      - name: 上传附件
        uses: actions/upload-artifact@v4
        with:
          path: build/release/WC3ModManager.exe
      - name: 下载附件
        uses: actions/download-artifact@v4
