# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:

      - name: cacheQt
        id: WindowsCacheQt
        uses: actions/cache@v1
        with:
          path: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch_install}}
          key: ${{ runner.os }}-Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          cached: ${{steps.WindowsCacheQt.outputs.cache-hit }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 1
            
      - name: build-mingw
        shell: cmd
        run: |
          mkdir build
          cd build
          qmake -r CONFIG+=release CONFIG+=qtquickcompiler ..\${{ env.targetName }}.pro
          make
      - name: package
        shell: cmd
        run: |
          windeployqt build\release\${{ env.targetName }}.exe
            
      - name: 上传附件
        uses: actions/upload-artifact@v4
        with:
          path: ${{ runner.workspace }}/_build/_deploy/*.exe
      - name: 下载附件
        uses: actions/download-artifact@v4
