name: C++ Build with Qt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # 或者其他支持Qt的环境，如macOS或Windows

    steps:

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
          version: 5.15.2
          cached: 'false'
    - name: ubuntu install GL library
      run: sudo apt-get install -y libglew-dev libglfw3-dev
    - uses: actions/checkout@v4
      with:
          fetch-depth: 1
    - name: build ubuntu
      run: |
          qmake
          make
    
        # qmake -qt=5 ./WC3ModManager.pro
  # cmake . -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/qt5



    # 可选：上传构建产物
    #- name: Upload Artifact
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: your_binary_name
    #    path: path/to/your/binary # 指定构建产出的二进制文件路径

